# Customer Shopping Behavior Analysis

## Dataset Loading

### Loading the Dataset

The customer shopping behavior dataset was loaded into the Jupyter Notebook environment using the Pandas library to begin data preprocessing and analysis.

In [2]:
import pandas as pd

df = pd.read_csv("customer_shopping_behavior.csv")

### Previewing the Dataset

The first few rows of the dataset were displayed to understand the data structure, column names, and overall format of the dataset.

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

### Statistical Summary

Descriptive statistics were generated to analyze the distribution, central tendency, and variability of numerical features in the dataset.

In [4]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

### Comprehensive Data Summary

A complete summary of both numerical and categorical features was generated to gain deeper insights into the dataset structure and value distribution.

In [5]:
df.describe(include = "all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

## Data Preprocessing

### Missing Value Analysis

The dataset was checked for missing values to ensure data quality and identify any null entries before performing further analysis.

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

### Handling Missing Values

Missing values in the review rating column were imputed using the median rating of each product category to maintain data consistency and reduce the impact of outliers.

In [7]:
df["Review Rating"] = df.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.median()))

### Verifying Missing Values

The dataset was re-evaluated after data preprocessing to confirm that missing values were successfully handled.

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

### Standardizing Column Names

Column names were transformed into a consistent format by converting them to lowercase, replacing spaces with underscores, and renaming columns for better readability and easier querying.

In [9]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns = {"purchase_amount_(usd)" : "purchase_amount"})

### Viewing Updated Column Names

The updated column names were displayed to verify successful standardization and ensure consistency across the dataset.

In [10]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

## Feature Engineering

### Creating Age Groups

A new age group feature was created by dividing customers into quartile-based categories to support demographic analysis and customer segmentation.

In [11]:
# create a column age_group
labels = ["Young Adult", "Adult", "Middle-aged", "Senior"]
df["age_group"] = pd.qcut(df["age"], q = 4, labels = labels)

### Previewing Age Group Segmentation

The newly created age group categories were displayed alongside customer ages to validate the segmentation process.

In [12]:
df[["age","age_group"]].head(100)

    age    age_group
0    55  Middle-aged
1    19  Young Adult
2    50  Middle-aged
3    21  Young Adult
4    45  Middle-aged
..  ...          ...
95   37        Adult
96   32        Adult
97   21  Young Adult
98   20  Young Adult
99   26  Young Adult

[100 rows x 2 columns]

### Converting Purchase Frequency into Numerical Format

Purchase frequency values were transformed into numerical day-based intervals to enable quantitative analysis and customer purchasing behavior evaluation.

In [13]:
# create column purchase_frequency_days

frequency_mapping = {
    "Fortnightly": 14,
    "Weekly": 7,
    "Monthly": 30,
    "Quarterly": 90,
    "Bi-Weekly": 14,
    "Annually": 365,
    "Every 3 Months": 90
}

df["purchase_frequency_days"] = df["frequency_of_purchases"].map(frequency_mapping)

### Validating Purchase Frequency Conversion

The original purchase frequency values and their corresponding numerical representations were displayed to verify the accuracy of the transformation process.

In [14]:
df[["frequency_of_purchases", "purchase_frequency_days"]].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

### Reviewing Discount and Promotion Data

Discount application and promotional code usage data were examined to understand customer engagement with promotional offers.

In [15]:
df[["discount_applied","promo_code_used"]].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

### Checking Data Consistency

A validation check was performed to verify consistency between discount application and promotional code usage records.

In [16]:
(df["discount_applied"] == df["promo_code_used"]).all()

np.True_

### Removing Redundant Features

The promotional code column was removed from the dataset after confirming redundancy to improve data clarity and reduce unnecessary attributes.

In [17]:
df = df.drop("promo_code_used", axis = 1)

## PostgreSQL Integration

### Installing Database Connectivity Libraries

Required libraries were installed to enable connectivity between Jupyter Notebook and PostgreSQL for database operations and SQL analysis.

In [18]:
pip install psycopg2-binary SQLAlchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\laxmi\appdata\roaming\python\python313\site-packages (2.9.12)
Requirement already satisfied: SQLAlchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from SQLAlchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from SQLAlchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

### Loading Data into PostgreSQL

A connection was established between Jupyter Notebook and PostgreSQL using SQLAlchemy, and the processed dataset was successfully transferred into a database table for SQL-based business analysis.

In [19]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
username = "postgres"
password = "Lalli%400829"
host = "localhost"
port = "5432"
database = "Customer_Behavior_Analysis"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"
df.to_sql(table_name, engine, if_exists = "replace", index = False)


print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'Customer_Behavior_Analysis'.